### ISSUE TITLE
NumericInput parsing issues and questions

### ISSUE THREAD

**Issue by RudyTheDev** [RonenNess/Iguina#4]
While playing around with the `NumericInput`, I noticed a few immediate bugs:
* you cannot directly type `0.3`, as it won't let you type `.` after `0`
* even if you typed `.3`, you couldn't add a `0` as it gets trimmed
* typing `.1` and then deleting `1` would cause an exception
* trying to add a `0` before `1` would cause caret to move forward while the text doesn't change
* typing any invalid (unparsed) character before the final character would still move the caret forward

I decided to fix these, although I didn't realize what a rabbithole of edge cases I would encounter. I have currently fixed all the above and [added unit tests](https://github.com/RudyTheDev/Iguina/blob/misc-fixes/Iguina.Tests/NumericInputTests.cs) to cover all the cases I could think of. This was way more tricky than I initially expected.

Anyway, while doing all this, I encountered a couple questions that are more about UI design:
* Should the field trim zeros as soon as they are redundant? This is how I believe it is currently intended to work, although it currently only reduces `000` to `0`. So with changes, `002` becomes `2` and `-002` becomes`-2`, but also typing `1002` and then deleting `1` would end up with `2`.
* Should the field accept input of the form `.3` and `-.3`? In my version, I immediately convert these to `0.3` and `-0.3`.

The reason I bring up these two examples is because `TextInput` now has to consider what the child actually does with the `Value`, because having removed or added a character might actually not change the `Value` or indeed change the value by more than 1 character - both remove multiple and add multiple. I don't know if this is helpful from user's perspective. And I don't know if maintaining code with many edge cases is worth it from dev perspective.

**Comment by RonenNess** [comment]
Hi @RudyTheDev  thank you for this great input.

I fixed the bugs above. You warned me about a rabbit hole of edge cases so obviously I jumped right in head first . After some suffering I think its mostly covered.

Could you please do a PR with the test project you added? It would be a great addition we can expend on. If you're too lazy to do a PR because your branch has other things in it let me know and I'll just grab it from your repo.

About your questions:

> Should the field trim zeros as soon as they are redundant? This is how I believe it is currently intended to work, although it currently only reduces 000 to 0. So with changes, 002 becomes 2 and -002 becomes-2, but also typing 1002 and then deleting 1 would end up with 2.

Yes that is the intended behavior. I improved the code a little to match it.

> Should the field accept input of the form .3 and -.3? In my version, I immediately convert these to 0.3 and -0.3.

I added a new flag, `FixPrefixDecimalSeparator`. If its true, it will behave like you describe, If false, it will just not accept input starting with . or -..

About caret offset for invalid inputs - you are right there are some cases that invalid input correction may shift the caret and not in all cases its the expected behavior. But I consider this low priority issues that I will not solve for now as I'm already limited in time. If you want to sweep it up that would be nice but I think its not too bad as its only for invalid input and as long as it doesn't crash or mess up input I can live with that.

Thanks, and let me know if you want to PR or if I should take the test project from your repo!

**Comment by RudyTheDev** [comment]
Oh, sorry, I should have been more clear that my branch also had those issues fixed and a bunch of other corner cases, so you didn't need to fix them yourself yet.

I will submit a PR without conflicts so you can look at the changes. I did a bunch of small things, but then I encountered the NumericInput and it just went off the rails haha...

I'll comment on the PR.

**Comment by RonenNess** [comment]
Ah thanks man, sorry I missed your point that you actually fixed it. 
Anyway I may not be available for a few days so take your time, I'll take a look when I can.

Cheers
